python src/main_tmp.py --disease_name "trachoma"
python src/main_tmp.py --disease_name "schistosomiasis"
python src/main_tmp.py --disease_name "dengue"
python src/main_tmp.py --disease_name "leishmaniasis"
python src/main_tmp.py --disease_name "onchocerciasis"