illness_as_metaphor_themes = {
    "Metaphor and Stigma": "Sontag argues that diseases are often surrounded by metaphors that create stigma, framing illnesses in ways that imply shame or disgrace.",
    "Illness as a Punishment": "Sontag critiques the notion that diseases are seen as punishments for moral or personal failings, which unfairly blames the patient.",
    "Military Metaphors": "Sontag examines how illnesses are described using military language (e.g., 'battling cancer'), suggesting this implies that patients who don't recover are seen as not having fought hard enough.",
    "Illness as a Metaphor for Social and Cultural Issues": "Sontag discusses how illnesses are used metaphorically to represent broader social and cultural anxieties or issues, such as corruption or decay.",
    "Objectivity and Reality of Illness": "Sontag advocates for viewing illnesses in purely medical and scientific terms, without the baggage of metaphor, to reduce stigma and fear.",
    "Psychosomatic Explanations": "Sontag critiques explanations that link diseases to psychological states or emotional conditions, arguing this often leads to victim-blaming.",
    "Victim-Blaming": "Sontag addresses how metaphors can lead to blaming patients for their illnesses, suggesting they brought it upon themselves through their actions or thoughts.",
    "Fear and Anxiety Surrounding Illness": "Sontag explores how metaphorical thinking amplifies fear and anxiety about diseases, making them seem more terrifying than they are in medical terms.",
    "Dehumanization of Patients": "Sontag discusses how metaphorical language can dehumanize patients, reducing them to symbols of their illness rather than seeing them as individuals.",
    "The Role of Language in Shaping Perceptions of Illness": "Sontag emphasizes the power of language in shaping societal perceptions of diseases, influencing attitudes and behaviors toward those who are ill.",
    "Historical Context of Disease Metaphors": "Sontag examines how historical contexts have shaped the metaphors used to describe diseases, showing that these metaphors change over time.",
    "Illness and Identity": "Sontag discusses how illnesses can become a central part of a person's identity due to the strong metaphors associated with them.",
    "The Romanticization of Illness": "Sontag critiques how certain illnesses, like tuberculosis in the past, were romanticized and linked to creativity and sensitivity, which distorts their reality.",
    "Control and Power in Medical Discourse": "Sontag explores how those in power (e.g., doctors, policymakers) use metaphorical language to exert control over how diseases are understood and managed.",
    "The Influence of Literature and Art on Perceptions of Illness": "Sontag analyzes how literature and art have contributed to the metaphorical thinking about diseases, often reinforcing harmful stereotypes.",
    "Illness and the Body": "Sontag discusses the relationship between illness and the body, criticizing metaphors that make the body a battleground or a site of moral judgment.",
    "Cultural Variations in Disease Metaphors": "Sontag examines how different cultures use different metaphors for diseases, highlighting the variability and subjectivity in how illnesses are perceived.",
    "Illness as a Journey or Battle": "Sontag critiques the common metaphors of illness as a journey or battle, arguing they oversimplify the experience and put undue pressure on patients.",
    "The Impact of Illness Metaphors on Public Health Policy": "Sontag discusses how metaphorical thinking can influence public health policies, sometimes leading to misguided or harmful approaches to disease management.",
    "Psychological Impact of Disease Metaphors on Patients": "Sontag explores the psychological impact of metaphorical language on patients, showing how it can affect their self-perception and emotional well-being."
}
